"""4564745

Revision ID: 10b0ddbb837d
Revises: 08b9e8bca7fb
Create Date: 2021-07-03 12:34:10.178522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b0ddbb837d'
down_revision = '08b9e8bca7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
