"""4564745

Revision ID: 67ef09450461
Revises: 
Create Date: 2021-07-07 16:27:02.852973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ef09450461'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('fact_qliq_data1', sa.Integer(), nullable=True),
    sa.Column('fact_qliq_data2', sa.Integer(), nullable=True),
    sa.Column('fact_qoil_data1', sa.Integer(), nullable=True),
    sa.Column('fact_qoil_data2', sa.Integer(), nullable=True),
    sa.Column('forecast_qliq_data1', sa.Integer(), nullable=True),
    sa.Column('forecast_qliq_data2', sa.Integer(), nullable=True),
    sa.Column('forecast_qoil_data1', sa.Integer(), nullable=True),
    sa.Column('forecast_qoil_data2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
