"""4564745

Revision ID: 743ea2ca6d25
Revises: 10b0ddbb837d
Create Date: 2021-07-03 12:45:40.605030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743ea2ca6d25'
down_revision = '10b0ddbb837d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'value')
    # ### end Alembic commands ###
