"""4564745

Revision ID: e0e3317f0a43
Revises: 743ea2ca6d25
Create Date: 2021-07-03 13:17:21.792341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e3317f0a43'
down_revision = '743ea2ca6d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'day')
    # ### end Alembic commands ###
